# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sc15NBJ7XNbtPgtqN81BzuMCililEOqr
"""

n = 5
fact = 1

for i in range(1, n + 1):
    fact = fact * i

print("Factorial of", n, "=", fact)